### ISSUE TITLE
Reduzir a imagem da página inicial para metade do tamanho

### ISSUE THREAD

**Issue by pintasart** [pythonpt/pythonpt.github.io-src#11]
Propostas: 
1. Reduzir a imagem para metade do tamanho por forma que  toda a página caiba no ecrã e não ser necessário fazer scroll down.

2. Oportunidade de melhoria: colorir a cobrinha com as cores azul e amarelo ( padrão da serpente do logo oficial python)

3. "Cereja em cima do bolo": colorir a bandeirinha de verde/fermelho a indicar  a nossa Portugalidade.

A imagem está  porreira. ;)

**Comment by lapisdecor** [comment]
Ou pinto o desenho todo, ou fica como está. A cobra não pode ficar com essas cores que já experimentei e não fica bem. Colocar côr só num elemento ou dois dá enfase a esses elementos e isso desiquilibra o desenho. A escolha do monocromático foi para ficar como no site checo que tinha um design que gostavamos, além disso combina com o resto do site.

**Comment by lapisdecor** [comment]
Ok a imagem foi reduzida e pintada. Vou fechar esta issue.
