### ISSUE TITLE
Páginas que faltam

### ISSUE THREAD

**Issue by lapisdecor** [pythonpt/pythonpt.github.io-src#15]
- videos
- tutoriais (isto não se devia chamar guias?)
- empregos
- criar artigos para o blog
- criar screencasts para o youtube (e incluir o canal de youtube na página dos videos)

**Comment by lapisdecor** [comment]
Tirando os empregos que só tem brevemente, acho que estamos prontos para publicação.
Talvez meter imagens em mais páginas tornasse as páginas mais apelativas.

**Comment by pintasart** [comment]
As páginas estão todas construídas.
