### ISSUE TITLE
Imagens não ficam centradas no rst

### ISSUE THREAD

**Issue by lapisdecor** [pythonpt/pythonpt.github.io-src#17]
Para centrar uma imagem, usa-se `align: center`, ex:
```
.. image:: stars.jpg
    :width: 200px
    :align: center
    :height: 100px
    :alt: alternate text
```
No entanto isto não está a funcionar no nosso caso. Suspeito que possa ter a ver com o bootstrap ou com alguma definição no código do template.

Para já isto não é prioritário, visto que as imagens ficam bem encostadas à esquerda, mas podemos vir a ter de centrar imagens, por ex em artigos do blog.

**Comment by pintasart** [comment]
Vou analisar isso

**Comment by pintasart** [comment]
Proposto PR #18
