### ISSUE TITLE
The menu is ordered alphabetically

### ISSUE THREAD

**Issue by lapisdecor** [pythonpt/pythonpt.github.io-src#3]
Except the blog, which comes as last item, the rest of the links in the menu are presented by alphabetic order. This wouldn't be a problem if the home page wasn't one of them.

**Comment by lapisdecor** [comment]
According to this [comment](https://github.com/getpelican/pelican/issues/420#issuecomment-16080572), its possible to sort the pages if they include a page-order metadata.

**Comment by lapisdecor** [comment]
Pelos vistos o @pintasart  já resolveu esta issue. Henrique queres explicar como fizeste para ficar aqui documentado?

**Comment by pintasart** [comment]
Podes fazer pelo pelicanconf.py e depois iterar no template chamando a Tag certa. 
Na verdade fiz um mix, editei directamente no template uma parte e iterei outra.
