### ISSUE TITLE
Erro ao gerar o conteúdo usando o tema

### ISSUE THREAD

**Issue by nmariz** [pythonpt/pythonpt.github.io-src#4]
Ao gerar o conteúdo com `make publish` o seguinte erro é gerado:

`CRITICAL: TypeError: not all arguments converted during string formatting`

Este erro foi reportado no repositório oficial do [Pelican](https://github.com/getpelican/pelican), no [Issue #2489](https://github.com/getpelican/pelican/issues/2489).

**Comment by lapisdecor** [comment]
Acho que corrigi o problema, fiz um fix directamente na master, mas para a próxima faço um PR. Quando puderes podes testar para ver se o problema desapareceu?

**Comment by nmariz** [comment]
Funcionou. Nesta fase não é necessário fazer PR. Thanks!
