### ISSUE TITLE
Error 404 author

### ISSUE THREAD

**Issue by pintasart** [pythonpt/pythonpt.github.io-src#42]
http://python.pt/author/nuno-mariz/
http://python.pt/author/luis-louro/

Error 404 not found

**Comment by lapisdecor** [comment]
This seems to work locally.

**Comment by lapisdecor** [comment]
This looks like a template error, since the link exists here:
http://python.pt/author/nuno-mariz.html
http://python.pt/author/luis-louro.html

**Comment by lapisdecor** [comment]
The error can also be in pelicanconf since we have there:
AUTHOR_URL = 'author/{slug}/'
AUTHOR_SAVE_AS = 'author/{slug}.html'

**Comment by lapisdecor** [comment]
Problem solved, I just change to AUTHOR_URL = 'author/{slug}.html' and it now works.
